export default {
	UPDATE_EDIT_EVENT: 'UPDATE_EDIT_EVENT',
	REGISTER: "REGISTER",
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	ADD_EVENT: "ADD_EVENT",
	GET_EVENTS: "GET_EVENTS",
	EDIT_EVENTS: "EDIT_EVENTS",
	GET_EVENT: "GET_EVENT",
	DELETE_EVENTS: "DELETE_EVENTS"
}
